name: Release
on:
  push:
    tags:
      - "v*"
env:
  GO_VERSION: "1.20"
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install rpm
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v1.0.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.QC_PAT }}
